### ISSUE TITLE
Crash every 10-20 minutes

### ISSUE THREAD

**Issue by VoodooLikesToCode** [Chummycho/Prey_Public#2]
When playing the modpack it crashes randomly after 10-20 minutes. I haven't found a specific trigger yet, but I do have the crash log: https://mclo.gs/ufDIn56.
I can't read it though. I hope this is helpful!

**Comment by Chummycho** [comment]
I believe this is actually an issue with your Java flags. I'm not 100% sure yet though and I'll do more investigating.

**Comment by Chummycho** [comment]
It also might just be an issue with your Java if it is manually installed. Try updating your GPU drivers as well.

**Comment by VoodooLikesToCode** [comment]
Yeah, i think i solved the issue. It might've been because i was running an ancient bios. Now that that is updated it doesn't crash anymore.
