### ISSUE TITLE
Tetra modular items are unenchantable

### ISSUE THREAD

**Issue by Thaumy810975** [Chummycho/Prey_Public#4]
Tetra modular items can't be enchanted in game.
Tetra workbench, enchantment table, anvil, and even enchant command won't work. 
It seems that the issue is caused by a incompatibility between tetra and universal enchants. Hopefully you can fix this. It's really annoying to be unable to upgrade my tools.

**Comment by Chummycho** [comment]
Thanks for finding this. I fixed it a few updates ago but I forgot to close this issue.
